[package]
name = "hades2"
version = "0.1.0"
edition = "2021"

[features]
serde = ["dep:serde"]

[dependencies]
anyhow = "1.0"
lz4_flex = "0.11"
thiserror = "1.0"
dirs = "5.0"
serde = { version = "1.0", optional = true }

[target.'cfg(target_os="windows")'.dependencies]
winreg = "0.52"
