[package]
name = "hades2-bindings"
version = "0.1.0"
edition = "2024"

[dependencies]
hades2 = { path = "../../crates/hades2", features = ["serde"] }
serde_json = "1.0.117"
wasm-bindgen = "0.2.92"

[lib]
crate-type = ["cdylib"]
